### ISSUE TITLE
What's the license and rate limit

### ISSUE THREAD

**Issue by leedstyh** [antoinevulcain/Financial-Modeling-Prep-API#1]
Hi, nice API. 

And that's the license and rate limit about this API?

And also historical price is very helpful, but why volume is missing. I think providing OHLCV data is better.

**Comment by antoinevulcain** [comment]
Hi,

Thanks, there are no limit on the number of API requests per day. 

You are right OHLCV data would be a good idea. In collaboration with the tech team we will implement it.

Thanks a lot for the feedbacks.

**Comment by leedstyh** [comment]
Thanks @antoinevulcain
