### ISSUE TITLE
Monetization plans? 

### ISSUE THREAD

**Issue by navkast** [antoinevulcain/Financial-Modeling-Prep-API#10]
Antoine / Mark, 

I'm totally amazed that this is free. Thank you for that. It saves me a huge amount of time from parsing XBRL. Do you have any plans on adding paid service tiers?

Cheers!

**Comment by antoinevulcain** [comment]
Hello Naveen,

Not for now we are just working to improve our API to make it more complete and accurate and add new data and exchange rate,

Here are some new endpoints that we have just finished, there are beta but we changed the keys for camel case convention and add some fields in the cash flow statement:

https://financialmodelingprep.com/api/v3.1/financials/income-statement/AAPL

https://financialmodelingprep.com/api/v3.1/financials/income-statement/AAPL?period=quarter

https://financialmodelingprep.com/api/v3.1/financials/balance-sheet-statement/AAPL

https://financialmodelingprep.com/api/v3.1/financials/balance-sheet-statement/AAPL?period=quarter

https://financialmodelingprep.com/api/v3.1/financials/cash-flow-statement/AAPL

https://financialmodelingprep.com/api/v3.1/financials/cash-flow-statement/AAPL?period=quarter 

Best,

**Comment by navkast** [comment]
OK thanks. Let me know if I can help.
