### ISSUE TITLE
v3.1 beta financials endpoints issues

### ISSUE THREAD

**Issue by navkast** [antoinevulcain/Financial-Modeling-Prep-API#11]
Please let me know if you prefer a different approach (emails, ticketing system, etc) for issue tracking. **You can also tell me to go away!** I don't want to be rude or bother your work.

Otherwise, I was hoping this could be an ongoing list of bugs for the 3.1 endpoint you mentioned in #10. I know it's beta so maybe my testing could help.

The end point sends a 200 with the following body:
```
{
  "error" : "This request is limited to 1 symbols to prevent exceeding server response time.",
  "message" : "Contact info@financialmodelingprep.com for more details"
}
```
when querying things without financial statements: 
- e.g,. an ETF: https://financialmodelingprep.com/api/v3.1/financials/income-statement/SPY
- e.g., a symbol that doesn't exist: https://financialmodelingprep.com/api/v3.1/financials/income-statement/SYMBOL_NO_EXIST

Expected behavior: Symbols that don't have financial statements should either return a `204 NO CONTENT` with no body, or a `404` with an error body. Even a 200 with no body could be better.

**Comment by antoinevulcain** [comment]
here is the body that we created for this type of request 👍 
{
  "error" : "No content for this symbol . Please retry or visit the documentation (https://financialmodelingprep.com/developer/docs/) for more options.",
  "message" : "Contact info@financialmodelingprep.com for more details"
}

example:
[https://financialmodelingprep.com/api/v3.1/financials/income-statement/SPY](https://financialmodelingprep.com/api/v3.1/financials/income-statement/SPY)

Could you test and let me know if it works on your end?
