### ISSUE TITLE
Text formatting issue with Balance Sheet CSV PP&E Line

### ISSUE THREAD

**Issue by ebeldner** [antoinevulcain/Financial-Modeling-Prep-API#14]
In the CSV file format for Balance Sheets, the PP&E line has a textual formatting issue that causes the line title ("Property Plant & Equipment") to get split across 2 cells when opened by Google Sheets or Excel. 

As formatted in CSV file:
`Property," Plant & Equipment Net"`

Screenshot of effect when opened in Google Sheets:
<img width="1133" alt="Screen Shot 2019-11-26 at 10 28 25 AM" src="https://user-images.githubusercontent.com/1638276/69661675-ad012300-1037-11ea-9eb5-92fc497ae64a.png">

**Comment by antoinevulcain** [comment]
@ebeldner It's corrected

**Comment by antoinevulcain** [comment]
https://financialmodelingprep.com/api/v3/financials/balance-sheet-statement/AAPL?period=quarter&datatype=csv
