### ISSUE TITLE
Is Cross-domain access enabled.

### ISSUE THREAD

**Issue by suraj-kawale-au2** [antoinevulcain/Financial-Modeling-Prep-API#2]
![image](https://user-images.githubusercontent.com/13823258/60382528-ce0e1980-9a81-11e9-8ef5-4584b9f95ba7.png)
Nice api. 
I have been using it for my Bootcamp project to build a stock portfolio app.  It worked fine before but since yesterday it starts giving me CORS error and I have to specify some headers.

Here is a sample program I am trying to create: https://repl.it/@surajk202/market.

**Comment by financialmodellingprep** [comment]
Hello Suraj,

Can you try this code and see if you have the CORS issue?

https://jsfiddle.net/Financialmodelingprep/h54o01r2/

**Comment by suraj-kawale-au2** [comment]
Thanks for reverting back. 
I see in your code u used `crossDomain: true`. Even I also used it. But still, it was showing CORS error yesterday. But today it didn't show any CORS error and API calls worked awesomely. Is there are some restrictions on the number of calls? Because yesterday I made too many calls maybe it was showing so.

**Comment by financialmodellingprep** [comment]
We don't but our host provider has some DDos algorithm that protects our infrastructure they have been triggered.
We have discussed with them and now everything should work properly.
If you have any other issues let us know and we will do the necessary to solve them.

**Comment by suraj-kawale-au2** [comment]
Ok. That's why maybe those errors appeared. Thanks a lot for reverting back and providing a great API for developers out there.
