### ISSUE TITLE
Standardized vs. As Reported Data

### ISSUE THREAD

**Issue by mksamelson** [antoinevulcain/Financial-Modeling-Prep-API#20]
Hi,

Is the fundamental data standardized, as-reported, or are both available?

If data is restated is that indicated and if so is the original reported data available? 

Thanks

**Comment by antoinevulcain** [comment]
Hi @mksamelson ,

The data is standardized meaning: when we have the value as reported in the 10-K or 10-Q in the SEC filing we fill it, when we don't we calculated it, example:
GoodWill and intangible assets:

In the SEC 10-Q xbrl tag: us-gaap_Goodwill
Then we add up the intangibles assets if there are so we match our variable name.

For the Revenue Growth we make the calcul ourselves : R1 - R0 / R0.

So it is as-reported but when we can we do some calculations to standardized the data to match our endpoints variables names.

**Comment by mksamelson** [comment]
If data is restated is that indicated and if so is the original reported data available?

**Comment by antoinevulcain** [comment]
@mksamelson the data is restated to match the output json we are developing an as-reported endpoint with all xbrl tags.

We follow this guideline for all our calculations:

https://xbrl.us/wp-content/uploads/2015/03/PreparersGuide.pdf
