### ISSUE TITLE
Adjusted Close Prices for US Securities

### ISSUE THREAD

**Issue by mksamelson** [antoinevulcain/Financial-Modeling-Prep-API#23]
Hi,

Are these split adjusted, dividend adjusted, or both?  Any chance of getting them from further back than 2015?  Are you calculating them or deriving them from somewhere where they are pre-calculated?

**Comment by antoinevulcain** [comment]
@mksamelson you can get them from beyond 2015:

https://financialmodelingprep.com/api/v3/historical-price-full/stock_dividend/AAPL

https://financialmodelingprep.com/api/v3/historical-price-full/stock_split/AAPL

The split and dividend are not adjusted, the historical data prices however have a property called adjClose where the close is adjusted to reflect the change.
