### ISSUE TITLE
Issue with volume value for Oct 31st 2019 data

### ISSUE THREAD

**Issue by coffincw** [antoinevulcain/Financial-Modeling-Prep-API#26]
The volume value for 10/31/2019 is 100x the actual value on that day (and also slightly off the actual volume). This applies to at least every stock using the `historical-price-full` endpoint, I haven't tested with market indexes, crypto, or anything else.

**Example - Using DIS stock ticker**
Request: https://financialmodelingprep.com/api/v3/historical-price-full/dis?timeseries=100

*October 31st 2019* JSON block:
```
...
  }, {
    "date" : "2019-10-31",
    "open" : 129.53,
    "high" : 130.15,
    "low" : 128.75,
    "close" : 129.92,
    "adjClose" : 129.92,
    "volume" : 9.6223E8,
    "unadjustedVolume" : 9.6223E8,
    "change" : -0.39,
    "changePercent" : -0.301,
    "vwap" : 129.60667,
    "label" : "October 31, 19",
    "changeOverTime" : -0.00301
  }, {
...
```

The actual volume should be 9628300 according to yahoo finance and nasdaq:
![image](https://user-images.githubusercontent.com/24260228/75952925-176b0000-5e7e-11ea-8170-8bf20a7bfe6d.png)
![image](https://user-images.githubusercontent.com/24260228/75953140-b7288e00-5e7e-11ea-88fe-e18e68818cb6.png)

**Comment by antoinevulcain** [comment]
@coffincw Yes you right thanks for pointing this out, I'll correct that asap

**Comment by antoinevulcain** [comment]
@coffincw Should be fixed now
