### ISSUE TITLE
Key metrics not up-to-date

### ISSUE THREAD

**Issue by kennethkichan** [antoinevulcain/Financial-Modeling-Prep-API#29]
Hi there,

Noticed that 2019-12-31 data has not been updated for the following APIs
https://financialmodelingprep.com/api/v3/company-key-metrics/FB
https://financialmodelingprep.com/api/v3/financial-statement-growth/FB

Thank you for the API, very good to use

**Comment by TarjinderSingh** [comment]
Also, the historical prices https://financialmodelingprep.com/api/v3/historical-chart/1min/%5EGSPC for indices are also not updated since yesterday.

**Comment by antoinevulcain** [comment]
@TarjinderSingh It's running again for the history I had to make some changes for #28 and #27 I add 400 data endpoint to cover the full day. It will work now.

@kennethkichan Yes for this two endpoint we are on it, we are making it very much cleaner I think by the end of the week it should be ready on both APIs.

**Comment by TarjinderSingh** [comment]
@antoinevulcain that's great - thanks so much!

**Comment by kennethkichan** [comment]
Thanks for the update, appreciate it!
