### ISSUE TITLE
Getting ERR_INCOMPLETE_CHUNKED_ENCODING error while requesting.

### ISSUE THREAD

**Issue by suraj-kawale-au2** [antoinevulcain/Financial-Modeling-Prep-API#3]
![image](https://user-images.githubusercontent.com/13823258/60711746-2a19e780-9f33-11e9-9cee-71998da5bfb8.png)
I am getting this error from last night when I am requesting on this API : https://financialmodelingprep.com/api/v3/company/stock/list

How many requests is allowed in a day?

**Comment by financialmodellingprep** [comment]
Hello,

Could you try now?

you can do 5 requests per second, with a burst of 15, which is equivalent to 432,000 requests/day or 12,960,000 requests per month,

let us know if the endpoint is working now,

Best

**Comment by suraj-kawale-au2** [comment]
Thanks, It works now. But still, there is some CORS error after certain amount request.
![image](https://user-images.githubusercontent.com/13823258/60725592-1da78600-9f57-11e9-8d06-a20cab5b5102.png)

**Comment by financialmodellingprep** [comment]
Hello,

The error status (503) means that the amount of requests exceeded the number of allowed requests per second.

Are you doing more than 5 requests per second?

Could you console.log the time at each request so we can see if it exceeds the amount. 

Best,

**Comment by suraj-kawale-au2** [comment]
Hey,
I have using the API in a for loop to construct a data in table format. I'll use some another approach. Thanks for reverting.

**Comment by suraj-kawale-au2** [comment]
Now when I used recursion to create a ticker and making 1 request per second to an api. It shows like this.
![image](https://user-images.githubusercontent.com/13823258/61055178-8cc92280-a40e-11e9-9e96-fe1155b9ee26.png)
Here is the code:- https://repl.it/@surajk202/ticker-1
Actually, I am creating a stock project for learning sake. I have no intention of earning from it.

**Comment by financialmodellingprep** [comment]
Could you try now? We increased server timeout response time. It should work now

**Comment by suraj-kawale-au2** [comment]
Yes, It works now. Thanks a lot again for the support and reverting back. I have reduced calls myself so other serious users of API doesn't fall into trouble.

**Comment by financialmodellingprep** [comment]
Happy that it works let us know if you have any problems in the future it is always a pleasure to help
