### ISSUE TITLE
Link error in README.md

### ISSUE THREAD

**Issue by victor-david** [antoinevulcain/Financial-Modeling-Prep-API#38]
Sample in README.md says:

> Single Currency such as Euro-dollars
> Currency exchange rate such as Euro-dollars (EUR/USD)
> 
> https://financialmodelingprep.com/api/forex/v3/EURUSD

Link doesn't work, gives: _Whitelabel Error Page_. Note that "forex" and "v3" are reversed. Should be:

https://financialmodelingprep.com/api/v3/forex/EURUSD

**Comment by antoinevulcain** [comment]
Thanks! corrected appreciate :)
