### ISSUE TITLE
Historical Market Index change calculation

### ISSUE THREAD

**Issue by victor-david** [antoinevulcain/Financial-Modeling-Prep-API#39]
Hi and thanks for the API. Using, for example:
https://financialmodelingprep.com/api/v3/historical-price-full/index/%5EAXJO

returns:
~~~json
{
  "symbol" : "^AXJO",
  "historical" : [ {
    "date" : "2020-04-09",
    "open" : 5206.899902,
    "high" : 5387.299805,
    "low" : 5206.899902,
    "close" : 5387.299805,
    "adjClose" : 5387.299805,
    "change" : -180.3999,
    "changePercent" : -3.465,
    "label" : "April 09, 20",
    "changeOverTime" : -0.03465
  }, etc.
~~~
Aren't the change (and changePercent) values incorrect, i.e reversed? The index went up 180.3999, not down. It seems that change = close - open, not open - close

Of course, it's easy to perform my own calculations from the open and close values, but thought I'd bring this to your attention in case this isn't on purpose.

**Comment by antoinevulcain** [comment]
@victor-david in 1 minute could you check the value?

**Comment by antoinevulcain** [comment]
@victor-david here I corrected the value you were right it was  open - close now it is close - open:

<img width="338" alt="Screen Shot 2020-04-14 at 10 15 21 PM" src="https://user-images.githubusercontent.com/15164400/79269907-779d8a80-7e9d-11ea-9249-5139013edd05.png">

**Comment by victor-david** [comment]
Yes, I see the positive values now when the index goes up. Many thanks!

**Comment by antoinevulcain** [comment]
Great 👍
