### ISSUE TITLE
What is the real meaning of 0? 

### ISSUE THREAD

**Issue by highsmallxu** [antoinevulcain/Financial-Modeling-Prep-API#40]
Hi,

Thanks for providing this API. I'm wondering that in the financials API, like this one https://fmpcloud.io/api/v3/income-statement/MA?apikey=<KEY>

You see a couple of 0 in the response. So do they really mean 0 or the data is missing/not existing in the original report? 

```JSON
{
  "date" : "2018-12-31",
  "symbol" : "MA",
  "period" : "FY",
  "revenue" : 14950000000,
  "costOfRevenue" : 0,
  "grossProfit" : 0,
}
```
Like this example, I would expect the grossProfit is 14950000000.

Hope my issue is clear.

Thanks

**Comment by antoinevulcain** [comment]
Hi,

This is right the 0 means that the data does not exist in the original report:

MA (Mastercard Inc) does not report its cost of revenue so this why you can see 0 for cost for costOfRevenue:

https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0001141391&type=10-K&dateb=&owner=exclude&count=40 you can look at the first report and see that it has only revenue as opposed to:

https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0000320193&type=10-k&dateb=&owner=exclude&count=40

where you can see that AAPL (Apple Inc) reports its cost of revenue .

However it make sense to make grossProfit it equals to its Revenue in case of the company does not report its costOfRevenue, so we are running a full script to update the value It will be done by tomorrow morning.

I will update you it is running now.

**Comment by highsmallxu** [comment]
Thank you so much for your quick response & quick action. 

Keep your good work! 👍

**Comment by antoinevulcain** [comment]
Hi,

Quick update we have run all the script and you can see all the value for grossProfit of MA now : 

```
[ {
  "date" : "2019-12-31",
  "symbol" : "MA",
  "period" : "FY",
  "revenue" : 16883000000,
  "costOfRevenue" : 0.0,
  "grossProfit" : 16883000000,
  "grossProfitRatio" : 1.0,
  "researchAndDevelopmentExpenses" : 0.0,
  "generalAndAdministrativeExpenses" : 5763000000,
  "sellingAndMarketingExpenses" : 0.0,
  "otherExpenses" : 1456000000,
  "operatingExpenses" : 7219000000,
  "costAndExpenses" : 7219000000,
  "interestExpense" : 224000000,
  "depreciationAndAmortization" : 1663000000,
  "ebitda" : 11327000000,
  "ebitdaratio" : 0.670911567849,
  "operatingIncome" : 9664000000,
  "operatingIncomeRatio" : 0.572410116685,
  "totalOtherIncomeExpensesNet" : 67000000,
  "incomeBeforeTax" : 9731000000,
  "incomeBeforeTaxRatio" : 0.576378605698,
  "incomeTaxExpense" : 1613000000,
  "netIncome" : 8118000000,
  "netIncomeRatio" : 0.480838713499,
  "eps" : 7.98,
  "epsdiluted" : 7.94,
  "weightedAverageShsOut" : 1017000000,
  "weightedAverageShsOutDil" : 1022000000
}

```

**Comment by highsmallxu** [comment]
Thanks!
