### ISSUE TITLE
Close and Adjusted Close is identical and adding endpoints for dividends and splits to documentation

### ISSUE THREAD

**Issue by legout** [antoinevulcain/Financial-Modeling-Prep-API#42]
Hello,

stock splits and dividends are available:

[https://financialmodelingprep.com/api/v3/historical-price-full/stock_dividend/AAPL]()

[https://financialmodelingprep.com/api/v3/historical-price-full/stock_split/AAPL]()

So, historical price data could be adjusted for dividends and splits. However, as far as I can see,  historical close and adjClose data are identical. 

Regards,
legout

**Comment by antoinevulcain** [comment]
@legout can you give precise (date, calcul, display) for my end to do to it

**Comment by legout** [comment]
I am sorry, tested it again and now everything is fine. 
I've tested it yesterday, and I was sure, that close and adjust close was the same. I'm sorry.

However, one "issue" remains. I have compared your data to the data from yahoo finance. Your adjusted close is not identical to the one from yahoo finance, whereas close, open, high and low are identical. 

**IBM**
![bokeh_plot-7](https://user-images.githubusercontent.com/1469563/80233324-9565af00-8656-11ea-8d6c-bb46ee468af1.png)
![bokeh_plot-8](https://user-images.githubusercontent.com/1469563/80233330-9991cc80-8656-11ea-8069-feecb6ce9c18.png)

Furthermore, there is a spike in your volume data. I found this for several stocks (date: 10/31/19). 

**IBM**
![bokeh_plot-6](https://user-images.githubusercontent.com/1469563/80233445-c940d480-8656-11ea-8dc1-76de7aa4dc4d.png)
**MSFT**
![bokeh_plot-9](https://user-images.githubusercontent.com/1469563/80233619-0ad17f80-8657-11ea-9ea6-499d48b877a5.png)

**Comment by antoinevulcain** [comment]
@legout Great happy to hear that! 

the spike for the volume I'm checking now seems to be about October 2019 on the chart

**Comment by legout** [comment]
Yes. It's on 31 October 2019. I saw this spike for AAPL, MSFT, GOOGL, IBM, MMM, ... 
Maybe for every US stock?

**Comment by antoinevulcain** [comment]
can you try now?

**Comment by antoinevulcain** [comment]
just for IBM

**Comment by legout** [comment]
Looks good for **IBM**

[https://financialmodelingprep.com/api/v3/historical-price-full/IBM?from=2019-10-30&to=2019-11-02](https://financialmodelingprep.com/api/v3/historical-price-full/IBM?from=2019-10-30&to=2019-11-02)

```

{
  "symbol" : "IBM",
  "historical" : [ {
    "date" : "2019-10-30",
    "open" : 133.83,
    "high" : 135.28,
    "low" : 133.2,
    "close" : 135.25,
    "adjClose" : 132.29,
    "volume" : 2252700.0,
    "unadjustedVolume" : 2252700.0,
    "change" : 1.42,
    "changePercent" : 1.061,
    "vwap" : 134.57667,
    "label" : "October 30, 19",
    "changeOverTime" : 0.01061
  }, {
    "date" : "2019-10-31",
    "open" : 135.11,
    "high" : 135.25,
    "low" : 133.23,
    "close" : 133.73,
    "adjClose" : 130.8,
    "volume" : 3412100.0,
    "unadjustedVolume" : 3412100.0,
    "change" : -1.38,
    "changePercent" : -1.021,
    "vwap" : 134.07,
    "label" : "October 31, 19",
    "changeOverTime" : -0.01021
  }, {
    "date" : "2019-11-01",
    "open" : 134.5,
    "high" : 135.56,
    "low" : 134.09,
    "close" : 135.53,
    "adjClose" : 132.56,
    "volume" : 3089800.0,
    "unadjustedVolume" : 3089800.0,
    "change" : 1.03,
    "changePercent" : 0.766,
    "vwap" : 135.06,
    "label" : "November 01, 19",
    "changeOverTime" : 0.00766
  } ]
}
```

Not so for **AAPL**
[https://financialmodelingprep.com/api/v3/historical-price-full/AAPL?from=2019-10-30&to=2019-11-02]()


```{
  "symbol" : "AAPL",
  "historical" : [ {
    "date" : "2019-10-30",
    "open" : 244.76,
    "high" : 245.3,
    "low" : 241.21,
    "close" : 243.26,
    "adjClose" : 243.26,
    "volume" : 3.09506E7,
    "unadjustedVolume" : 3.09506E7,
    "change" : -1.5,
    "changePercent" : -0.613,
    "vwap" : 243.25667,
    "label" : "October 30, 19",
    "changeOverTime" : -0.00613
  }, {
    "date" : "2019-10-31",
    "open" : 247.24,
    "high" : 249.17,
    "low" : 237.26,
    "close" : 248.76,
    "adjClose" : 248.76,
    "volume" : 3.47666E9,
    "unadjustedVolume" : 3.47666E9,
    "change" : 1.52,
    "changePercent" : 0.615,
    "vwap" : 245.06333,
    "label" : "October 31, 19",
    "changeOverTime" : 0.00615
  }, {
    "date" : "2019-11-01",
    "open" : 249.54,
    "high" : 255.93,
    "low" : 249.16,
    "close" : 255.82,
    "adjClose" : 255.82,
    "volume" : 3.77387E7,
    "unadjustedVolume" : 3.77387E7,
    "change" : 6.28,
    "changePercent" : 2.517,
    "vwap" : 253.63667,
    "label" : "November 01, 19",
    "changeOverTime" : 0.02517
  } ]
}```

**Comment by antoinevulcain** [comment]
@legout Yes I was just testing for IBM first to confirm it can be done

So I can do it for every stock I need to prepare a script and launch it.

**Comment by antoinevulcain** [comment]
@legout 

Should be fixed
