### ISSUE TITLE
Time format in  - "Stock Historical Price 1/5/15 etc minute historical stock prices with volume"

### ISSUE THREAD

**Issue by hanuor** [antoinevulcain/Financial-Modeling-Prep-API#43]
Hi,
I'd like to know that the time the API returns is the UTC time?
I surfed through the docs but couldn't find any information on this.
API - https://financialmodelingprep.com/api/v3/historical-chart/5min/AAPL
Sample response - 
{
"date": "2020-04-28 13:45:00",
"open": 280.28,
"low": 280.27,
"high": 281.07,
"close": 281.02,
"volume": 17771578
}

The date here is in UTC or GMT?

**Comment by antoinevulcain** [comment]
Hi @hanuor 
It is: 
calNewYork.setTimeZone(TimeZone.getTimeZone("America/New_York"));

-> UTC-4

**Comment by hanuor** [comment]
Perfect. Thanks @antoinevulcain :)

**Comment by hanuor** [comment]
Hi @antoinevulcain,

I checked the data I was getting by hitting the API above with TradingView and Finnhub.
It seems that the API is returning wrong open/close/high/low data points.

I crosschecked this with AAPL, TSLA, AMZN and the data was incorrect.
Any specific reason for this? Can you please check it from your end?

Thanks!

**Comment by antoinevulcain** [comment]
Code of conduct :
Publishing others' private information, such as a physical or electronic address, without explicit permission

**Comment by hanuor** [comment]
Hi @antoinevulcain 
Wanted to check why you've closed the issue and added that comment?
I didn't share any private information?
Thanks!

**Comment by antoinevulcain** [comment]
@hanuor just for future comment please:

**Comment by hanuor** [comment]
Okay. No worries.
Can you please check and confirm if there's a mismatch in the numbers?
Let me know if I can help in anyway.

**Comment by antoinevulcain** [comment]
@hanuor just for future comment 

`Copyright protection does not extend to titles, names, slogans or short phrases, the Copyright Office has made that much very clear. You can not copyright your name, the title of your post or any short phrase that you use to identify a work.
`

So I am relaunching the server and watching  the value , I am also looking at the sync I will update this as soon as I find the issue

**Comment by hanuor** [comment]
Perfect. Thanks a lot, @antoinevulcain . Apologies for the above error that I made.

**Comment by antoinevulcain** [comment]
@hanuor can you make a quick check?

**Comment by hanuor** [comment]
Sure. Checking

**Comment by hanuor** [comment]
Just checked. The issue is still there. 
Can send you screenshots if it helps @antoinevulcain

**Comment by antoinevulcain** [comment]
Yes please can you send me attach a screen shoot I’ll analyse it and make sure to correct it

**Comment by hanuor** [comment]
Below is the image of the chart I'm using.
![Screenshot from 2020-04-30 22-21-51](https://user-images.githubusercontent.com/11363676/80737488-38c03380-8b31-11ea-8acc-75f52d99016c.png)

Below is the image of another API from where I'm comparing the data. (Check the 1st row)
Format is -> DATE OPEN CLOSE
![Screenshot from 2020-04-30 22-22-34](https://user-images.githubusercontent.com/11363676/80737569-57262f00-8b31-11ea-902a-5516f2cfba0c.png)

Below is the image of the OPEN and CLOSE numbers that I'm getting from this APi.
![Screenshot from 2020-04-30 22-22-52](https://user-images.githubusercontent.com/11363676/80737734-90f73580-8b31-11ea-88e5-5aa90e451aab.png)

As you can see there's a considerable difference in the Open and close prices. Hence the concern.

**Comment by hanuor** [comment]
Hi @antoinevulcain .
Any updates or alternatives to this?

**Comment by antoinevulcain** [comment]
@hanuor I'm highly into this since yesterday I will update you as soon as I find the issue but I start to find some potential reason such has issue i.e https://mkyong.com/hibernate/how-to-configure-the-c3p0-connection-pool-in-hibernate/

**Comment by hanuor** [comment]
Okay. Thanks for the update. Let me know whenever you find something interesting or need any help.
@antoinevulcain
