### ISSUE TITLE
Historical market index not updating

### ISSUE THREAD

**Issue by victor-david** [antoinevulcain/Financial-Modeling-Prep-API#44]
The historical market index price isn't updating, at least for certain symbols. For instance, as of today (April 30, 2020):

https://financialmodelingprep.com/api/v3/historical-price-full/index/%5EGSPC

reports historical up to April 29. All is well. But Dow Jones:

https://financialmodelingprep.com/api/v3/historical-price-full/index/%5EDJI

reports only up to April 27. If you use the hourly for Dow Jones:

https://financialmodelingprep.com/api/v3/historical-chart/1hour/%5EDJI

it does report April 28/29, plus today.

So something seems to be lagging (or failing) in the historical-price-full update.

**Comment by antoinevulcain** [comment]
@victor-david  Yes you are right for Dow Jones can you check now?

**Comment by victor-david** [comment]
It is indeed working again. Getting historical-price-full for Dow Jones through yesterday, April 29.

Thanks a lot!

**Comment by antoinevulcain** [comment]
Pleasure let me know as soon as you see something not accurate thanks again!
