### ISSUE TITLE
api/v3/company/stock/list is returning a trunkated Json

### ISSUE THREAD

**Issue by aviaplana** [antoinevulcain/Financial-Modeling-Prep-API#46]
The endpoint ```api/v3/company/stock/list```is broken, the response is being truncated at line 14031

**Comment by antoinevulcain** [comment]
@aviaplana yes I'm on it it's nginx

**Comment by aviaplana** [comment]
thanks mate!

**Comment by antoinevulcain** [comment]
can you test?

**Comment by antoinevulcain** [comment]
@aviaplana

**Comment by aviaplana** [comment]
working smoothly! Thanks for your work!
