### ISSUE TITLE
API versioning

### ISSUE THREAD

**Issue by Skitionek** [antoinevulcain/Financial-Modeling-Prep-API#47]
It is extremely problematic that your **API is changing day by day**. Week ago I have corrected library to use it and today I was notified that it started crashing because you **again** modified data structure!

Diff of mentioned old vs new response (`historical_price_full/FB,GOOG`):
```diff
  Object {
    "historicalStockList": Array [
      Object {
        "historical": Array [
          Object {
-           "adjClose": ----,
-           "change": ----,
-           "changeOverTime": ----,
-           "changePercent": ----,
            "close": ----,
            "date": ----,
-           "high": ----,
-           "label": ----,
-           "low": ----,
-           "open": ----,
-           "unadjustedVolume": ----,
-           "volume": ----,
-           "vwap": ----,
          },
        ],
        "symbol": ----,
      },
    ],
```
Please do introduce an **API versioning** or at least give developers some head start and time for adaptation of changes.

**Comment by antoinevulcain** [comment]
it is not supposed to have changed one second

**Comment by antoinevulcain** [comment]
I'm fixing #46 then I look at this

**Comment by antoinevulcain** [comment]
https://financialmodelingprep.com/api/v3/historical-price-full/AAPL,FB

**Comment by antoinevulcain** [comment]
@Skitionek check now please

**Comment by Skitionek** [comment]
Yes, it changed back. I would have hoped you have tests in place for this kind of issues.

Before you close this issue can you let me know what is your approach towards versioning? Should I open issue every time your API changes? Can I subscribe to any newsletter, changelog, be notified if things are about to change?

**Comment by TheEpicBigBoss** [comment]
I think a version control would be a nice thing. Or maybe a known date, like every two weeks, where all the changes and fixes get applied.

Are you planning on uploading the source code of this Api here to Github? Then all the new changes an fixes would be visible in the pull request right before they get applied. This would help to prepare for changes. And I think a lot of people here would help to develop and contribute code.

**Comment by antoinevulcain** [comment]
I have tests it just because I have updated nginx and uploaded an old version by mistake but everything is tested with DTO it cannot happened.

So the DTO cannot change for any reason.

if the DTO change then the version change -> v4 / v3.1 / v3.2

**Comment by antoinevulcain** [comment]
@TheEpicBigBoss I can't upload the code here, there is more than a billion request per day and many of them are just trying to hack / break the API (because it is free without limit) so it would be a breach of security to show the code even for a day on github
