### ISSUE TITLE
Majors Indexes endpoint is not showing the right data

### ISSUE THREAD

**Issue by JoshuaR503** [antoinevulcain/Financial-Modeling-Prep-API#50]
As of May 5 2020 at 10:40 AM, the Dow Jones Industrial Average is trading at around 24,000 points, Nasdaq at 8,880, and the S&P 500 at 2,890. 

If I make a request to the endpoint `https://financialmodelingprep.com/api/v3/majors-indexes`, the response will be: 
`{
      "ticker": ".DJI",
      "changes": 147.029,
      "price": 23775.3,
      "indexName": "Dow Jones"
    },
    {
      "ticker": ".IXIC",
      "changes": 162.608,
      "price": 8873.32,
      "indexName": "Nasdaq"
    },
    {
      "ticker": ".INX",
      "changes": -46.5701,
      "price": 2863.39,
      "indexName": "S&P 500"
    }`

How can we fix this?

**Comment by antoinevulcain** [comment]
new endpoint : https://financialmodelingprep.com/api/v3/quotes/index

**Comment by JoshuaR503** [comment]
@antoinevulcain, thank you for your response. I just need to get the major american indexes. The endpoint you provided contains global indexes - that is great, but not what I was expecting.

**Comment by antoinevulcain** [comment]
@JoshuaR503 It contains the majors us also Dow Jones Nasdaq S&P 500 you just need to filer,

also you can do that : 

https://financialmodelingprep.com/api/v3/quote/%5EDJI,%5EGSPC,%5EIXIC

you now you have the major US index ;)
