### ISSUE TITLE
Specifying the nature of ticker symbols

### ISSUE THREAD

**Issue by muziofg** [antoinevulcain/Financial-Modeling-Prep-API#7]
Specifying the nature of ticker symbols

The list of all ticker symbol supported ( https://financialmodellingprep.com/api/v3/company/stock/list ) is useful, but can be more useful

The data provided should contains information about the market exchange (example: NYSE, NASDAQ) and the type of financial instrument (example: distinguish between ETF and share)

**Comment by antoinevulcain** [comment]
Very good idea, we will implement it

**Comment by antoinevulcain** [comment]
@muziofg just added the exchange property you can now see what type of exchange the ticker belongs to

**Comment by muziofg** [comment]
I'm sorry, arrived too late for adding more comments.

I'm not sure about the meaningfulness of "exchange" and "exchangeShortName" labels if you use them to determine the nature of a ticker; equities are equities regardless of the stock exchange that are available (example: NYSE, NASDAQ or AMEX)

Also, the if the endpoint https://financialmodellingprep.com/api/v3/company/stock/list contain only ticker of public company, it would be nice to have an endpoint for ETF, another for indexes... etc etc

**Comment by muziofg** [comment]
Also, The endpoint https://financialmodellingprep.com/api/v3/company/stock/list must be updated to remove delisted company like NFX, ARRY or renamed like IPOA (now SPCE)

you can check old tickers with a mechanism like the CRON job described here https://github.com/antoinevulcain/Financial-Modeling-Prep-API/issues/8#issuecomment-584589926 ?

**Comment by TheEpicBigBoss** [comment]
Maybe these delisted companys should be moved to another endpoint so that they don't get completely removed because the historical data should be still available even if they are not active any more.

**Comment by antoinevulcain** [comment]
@muziofg yes, we will update it and also create a new endpoint with the delisted ones.

@TheEpicBigBoss yes it's a good idea we will keep the historical data, especially for machine learning that could use the data set to predict a stock removal or delisting.
