### ISSUE TITLE
Dividends, stock splits and/or adjusted close

### ISSUE THREAD

**Issue by legout** [antoinevulcain/Financial-Modeling-Prep-API#9]
Hello,

thanks for creating this api and providing all this data for free!

However, to use this data for backtesting financial models, I am missing dividends, stock splits and/or stock prices adjusted by dividends and stock splits. Is it be possible to get this data somehow?

Regards,
legout

**Comment by antoinevulcain** [comment]
We have that data, we are just testing that it is accurate and reliable it should be available very soon 
We will expose the new endpoints as soon as it’s ready

**Comment by antoinevulcain** [comment]
https://financialmodelingprep.com/api/v3/historical-price-full/stock_dividend/AAPL

https://financialmodelingprep.com/api/v3/historical-price-full/stock_dividend/AAPL

**Comment by legout** [comment]
Great news! Thanks.
